/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 ./src/public/models/anchovies_Slice_Fish_0.glb -o src/modules/item/components/Bacon.jsx -k -K -r public 
*/

import React, { useRef } from "react";
import { Gltf, useGLTF } from "@react-three/drei";
import BaconG from "../../../public/models/anchovies_Slice_Fish_0.glb";

const name = { src: BaconG };

export default function Bacon(props: any) {
   return (
      <group {...props} dispose={null}>
         <group name="Scene">
            <Gltf src={name.src.toString()} />
         </group>
      </group>
   );
}

useGLTF.preload("../../../public/models/anchovies_Slice_Fish_0.glb");
